name: "Deploy to Freemius"
description: "Uploads and deploys your plugin on Freemius"
inputs:
  sandbox:
    description: 'Sandbox mode'
    required: false
    default: false
  file_name:
    description: 'file to deploy'
    required: true
  version:
    description: 'tag version'
    required: true
  release_mode:
    description: 'release mode'
    required: false
    default: 'pending'
outputs:
  free_version:
    description: 'The Free version file'
  pro_version:
    description: 'The Pro version file'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'arrow-up-circle'  
  color: 'green'
